# Generated by Django 4.2 on 2023-04-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_film_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilmrelation',
            name='rate',
            field=models.PositiveIntegerField(choices=[(1, 'Ok'), (2, 'Fine'), (3, 'Good'), (4, 'Nice'), (5, 'Wow')], null=True),
        ),
    ]
