# Generated by Django 4.2 on 2023-04-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_filmdata_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmdata',
            old_name='photo',
            new_name='image',
        ),
    ]
