# Generated by Django 4.2 on 2023-04-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_rename_photo_filmdata_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='data',
        ),
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='film',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.DeleteModel(
            name='FilmData',
        ),
    ]
