# Generated by Django 4.2 on 2023-04-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_film_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='likes_count',
        ),
    ]
